In [2]:
import json
import requests
import pandas as pd
import geopandas as gpd
import plotly
import plotly.express as px

In [3]:
arrests = pd.read_pickle('../NYCParks-SAEC/results_df.pandas')

arrests = gpd.GeoDataFrame(arrests, 
                        geometry = gpd.points_from_xy(
                         arrests.longitude, 
                         arrests.latitude, crs='EPSG:4326'))

arrests

,arrest_key,arrest_date,pd_cd,pd_desc,ky_cd,ofns_desc,law_code,law_cat_cd,arrest_boro,arrest_precinct,...,y_coord_cd,latitude,longitude,geocoded_column,:@computed_region_f5dn_yrer,:@computed_region_yeji_bk3q,:@computed_region_92fq_4b7q,:@computed_region_sbqj_enih,:@computed_region_efsh_h5xi,geometry
0,238013474,2021-12-18T00:00:00.000,157,RAPE 1,104.0,RAPE,PL 1303501,F,Q,105,...,203954,40.72618713000002,-73.73523390399998,"{'type': 'Point', 'coordinates': [-73.73523390...",63,3,16,63,24337,POINT (-73.73523 40.72619)
1,236943583,2021-11-25T00:00:00.000,263,"ARSON 2,3,4",114.0,ARSON,PL 1501500,F,K,69,...,171320,40.63686750900007,-73.89158591899997,"{'type': 'Point', 'coordinates': [-73.89158591...",5,2,8,42,13827,POINT (-73.89159 40.63687)
2,234938876,2021-10-14T00:00:00.000,594,OBSCENITY 1,116.0,SEX CRIMES,PL 2631100,F,K,61,...,155739,40.59414516900005,-73.96041495199995,"{'type': 'Point', 'coordinates': [-73.96041495...",32,2,15,36,18183,POINT (-73.96041 40.59415)
3,234788259,2021-10-11T00:00:00.000,263,"ARSON 2,3,4",114.0,ARSON,PL 1501001,F,B,42,...,239616,40.82433953100008,-73.91036538099996,"{'type': 'Point', 'coordinates': [-73.91036538...",34,5,43,25,10929,POINT (-73.91037 40.82434)
4,234188790,2021-09-28T00:00:00.000,578,NaN,NaN,NaN,PL 2223001,M,B,44,...,246667,40.84370255600004,-73.92439508899997,"{'type': 'Point', 'coordinates': [-73.92439508...",50,5,42,27,10930,POINT (-73.92440 40.84370)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155502,222884924,2021-01-10T00:00:00.000,397,"ROBBERY,OPEN AREA UNCLASSIFIED",105.0,ROBBERY,PL 1601001,F,B,46,...,247605,40.846260031000035,-73.90175529499999,"{'type': 'Point', 'coordinates': [-73.90175529...",6,5,22,29,10935,POINT (-73.90176 40.84626)
155503,223918625,2021-02-03T00:00:00.000,792,WEAPONS POSSESSION 1 & 2,118.0,DANGEROUS WEAPONS,PL 2650303,F,K,67,...,180941,40.66330200400005,-73.92542497899994,"{'type': 'Point', 'coordinates': [-73.92542497...",61,2,17,40,17614,POINT (-73.92542 40.66330)
155504,224323770,2021-02-13T00:00:00.000,101,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,S,121,...,166367,40.623226819000074,-74.14922697299994,"{'type': 'Point', 'coordinates': [-74.14922697...",4,1,13,75,10700,POINT (-74.14923 40.62323)
155505,222599533,2021-01-04T00:00:00.000,792,WEAPONS POSSESSION 1 & 2,118.0,DANGEROUS WEAPONS,PL 2650303,F,K,73,...,188555,40.684194302000044,-73.91608474599997,"{'type': 'Point', 'coordinates': [-73.91608474...",55,2,17,46,13516,POINT (-73.91608 40.68419)
155506,224056881,2021-02-06T00:00:00.000,268,CRIMINAL MIS 2 & 3,121.0,CRIMINAL MISCHIEF & RELATED OF,PL 1451000,F,Q,102,...,190787,40.69022556600004,-73.82993153599993,"{'type': 'Point', 'coordinates': [-73.82993153...",46,3,46,60,24015,POINT (-73.82993 40.69023)

In [4]:
arrests.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 155507 entries, 0 to 155506
Data columns (total 25 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   arrest_key                   155507 non-null  object
 1   arrest_date                  155507 non-null  object
 2   pd_cd                        155478 non-null  object
 3   pd_desc                      155404 non-null  object
 4   ky_cd                        155404 non-null  object
 5   ofns_desc                    155404 non-null  object
 6   law_code                     155507 non-null  object
 7   law_cat_cd                   154114 non-null  object
 8   arrest_boro                  155507 non-null  object
 9   arrest_precinct              155507 non-null  object
 10  jurisdiction_code            155507 non-null  object
 11  age_group                    155507 non-null  object
 12  perp_sex                     155507 non-null  object
 13  perp_race                    155507 non-null  object
 14  x_coord_cd                   155507 non-null  object
 15  y_coord_cd                   155507 non-null  object
 16  latitude                     155507 non-null  object
 17  longitude                    155507 non-null  object
 18  geocoded_column              155507 non-null  object
 19  :@computed_region_f5dn_yrer  155489 non-null  object
 20  :@computed_region_yeji_bk3q  155487 non-null  object
 21  :@computed_region_92fq_4b7q  155489 non-null  object
 22  :@computed_region_sbqj_enih  155489 non-null  object
 23  :@computed_region_efsh_h5xi  155242 non-null  object
 24  geometry                     155507 non-null  geometry
dtypes: geometry(1), object(24)
memory usage: 29.7+ MB